config/routes.rb
Budgie::Application.routes.draw do
  root 'users#new'
  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'messages', to: 'conversations#index', as: 'messages'
  get 'favorites', to: 'favorites#index', as: 'favorites'
  resources :categories

  resources :companies do
    resources :users, :discounts
  end 

  resources :users do
    resources :companies, :discounts, :favorites
  end  

  resources :discounts do
    resources :messages, :conversations
  end
    
  resources :conversations do
      resources :messages  
  end 


  resources :messages, only: [:update]

  resources :invitations

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  # root to: 'users#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base

  belongs_to :user
  belongs_to :company

  

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]
  before_action :set_user_favorite
  # GET /favorites
  # GET /favorites.json
  def index
    # @favorites = Favorite.all
    @favorites = @user.favorites
    @users = User.all
    @companies = Company.all
  end

  # GET /favorites/1
  # GET /favorites/1.json
  def show
  end

  # GET /favorites/new
  def new
    @favorite = Favorite.new
  end

  # GET /favorites/1/edit
  def edit
  end

  # POST /favorites
  # POST /favorites.json
  def create
    @favorite = Favorite.new(favorite_params)

    respond_to do |format|
      if @favorite.save
        format.html { redirect_to user_favorites_path(@user), notice: 'Favorite was successfully created.' }
        format.json { render action: 'show', status: :created, location: @favorite }
      else
        format.html { render action: 'new' }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /favorites/1
  # PATCH/PUT /favorites/1.json
  def update
    respond_to do |format|
      if @favorite.update(favorite_params)
        format.html { redirect_to user_favorites_path(@user), notice: 'Favorite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /favorites/1
  # DELETE /favorites/1.json
  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to user_favorites_path(@user)}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favorite_params
      params.permit(:user_id, :company_id)
    end

    def set_user_favorite
      @user = User.find(params[:user_id])
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_form.html.erb
<%= form_for([@user, @favorite]) do |f| %>
  <% if @favorite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favorite.errors.count, "error") %> prohibited this favorite from being saved:</h2>

      <ul>
      <% @favorite.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.number_field :company_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favorites/edit.html.erb
<h1>Editing favorite</h1>

<%= render 'form' %>

<%= link_to 'Show', user_favorites_path(@user) %> |
<%= link_to 'Back', user_favorites_path(@user) %>

app/views/favorites/index.html.erb
<h4 style="color: white">FAVORITES</h4>



<div class="row">
<% @favorites.each do |favorite| %>
 
          <div class="col-md-4 col-sm-6">
          
             <div class="card-container manual-flip">
                <div class="card">
                    <div class="front">
                        <div class="cover">
                            <%=image_tag("/rotating_card_thumb.png")%>
                        </div>
                        <div class="user">
                          <%=image_tag(("/rotating_card_profile.png"), class: "img-circle")%>
                        </div>
                        <div class="content">
                            <div class="main">
                                <h3 class="name"><%= favorite.company.company_name %></h3> 

                            </div>
                           <div class="footer"> 
                          <button class="btn btn-danger btn-sm" href="#">
                          <%= link_to ' Delete ', user_favorite_path(@user, favorite), method: :delete, data: { confirm: 'Are you sure?' }, class: "fa fa-trash-o fa-md"%>
                          </button>
                          <button class="btn btn-success btn-sm" onclick="rotateCard(this)"><i class="fa fa-mail-forward"></i> Manual Flip</button>
                          </div>

                        </div>
                    </div> <!-- end front panel -->
                    <div class="back">
                        <div class="header">

                        </div> 
                        <div class="content">
                            <div class="main">
                            
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-simple" rel="tooltip" title="Flip Card" onclick="rotateCard(this)">
                                <i class="fa fa-reply"></i> Back
                            </button>
                            <div class="social-links text-center">
                                <a href="http://cretive-tim.com" class="facebook"><i class="fa fa-facebook fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="google"><i class="fa fa-google-plus fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="twitter"><i class="fa fa-twitter fa-fw"></i></a>
                            </div>
                        </div>
                    </div> <!-- end back panel -->
                </div> <!-- end card -->
            </div> 

            <!-- end card-container -->
            
        </div> <!-- end col sm 3 -->
<!--         <div class="col-sm-1"></div> -->


<% end %>
</div>

<script type="text/javascript">
    $().ready(function(){
        $('[rel="tooltip"]').tooltip();
        
    });
    
    function rotateCard(btn){
        var $card = $(btn).closest('.card-container');
        console.log($card);
        if($card.hasClass('hover')){
            $card.removeClass('hover');
        } else {
            $card.addClass('hover');
        }
    }
</script>


<p style="color: white; margin-top: 10px">Select a company</p>

<div class="row">
<% @companies.each do |company| %>
 
          <div class="col-md-4 col-sm-6">
          <%= link_to company_discounts_path(company.id) do %> 
             <div class="card-container manual-flip">
                <div class="card">
                    <div class="front">
                    <div class="cover">
                    <%=image_tag("/rotating_card_thumb.png")%>
                    </div>
                    <div class="user">
                    <%=image_tag(("/rotating_card_profile.png"), class: "img-circle")%>
                    </div>

                        <div class="content">
                            <div class="main">
                                <h3 class="name"><%= company.company_name.truncate(16) %></h3>
                               
                                
                            </div>
                            <div class="footer"> 
                        <button class="btn btn-simple">
          <%= link_to 'Favorite', user_favorites_path(@user, company_id: company.id), method: :post , class: "fa fa-heart ct-heart"%>
        </button>
                                
                                <button class="btn btn-simple" onclick="rotateCard(this)">
                                    <i class="fa fa-mail-forward"></i> Manual Flip
                                </button>
                            </div>
                        </div>
                    </div> end front panel


                    <div class="back">
                        <div class="header">
                            <h5 class="motto">"To be or not to be, this is my awesome motto!"</h5>
                        </div> 
                        <div class="content">
                            <div class="main">
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-simple" rel="tooltip" title="Flip Card" onclick="rotateCard(this)">
                                <i class="fa fa-reply"></i> Back
                            </button>
                            <div class="social-links text-center">
                                <a href="http://cretive-tim.com" class="facebook"><i class="fa fa-facebook fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="google"><i class="fa fa-google-plus fa-fw"></i></a>
                                <a href="http://cretive-tim.com" class="twitter"><i class="fa fa-twitter fa-fw"></i></a>
                            </div>
                        </div>
                    </div> <!-- end back panel
                </div> <!-- end card -->
            </div> 
            <% end %><!-- end card-container -->
        </div> <!-- end col sm 3 -->
<!--         <div class="col-sm-1"></div> -->

   
</div>
<% end %>
</div>

app/views/favorites/new.html.erb
<h1>New favorite</h1>

<%= render 'form' %>

<%= link_to 'Back', favorites_path %>

app/views/favorites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @favorite.user_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @favorite.company_id %>
</p>

<%= link_to 'Edit', edit_favorite_path(@favorite) %> |
<%= link_to 'Back', favorites_path %>