config/routes.rb
Budgie::Application.routes.draw do
  root 'users#new'
  # get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  get 'messages', to: 'conversations#index', as: 'messages'
  get 'favorites', to: 'favorites#index', as: 'favorites'
  resources :categories

  resources :companies do
    resources :users, :discounts
  end 

  resources :users do
    resources :companies, :discounts, :favorites
  end  

  resources :discounts do
    resources :messages, :conversations
  end
    
  resources :conversations do
      resources :messages  
  end 


  resources :messages, only: [:update]

  resources :invitations

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]
  # root to: 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :discounts, dependent: :nullify
  has_many :companies
  has_many :favorites
  has_many :sent_invitations, :class_name => 'Invitation', :foreign_key => 'sender_id'
  belongs_to :invitation
  has_secure_password
  
  before_create :set_invitation_limit

  # attr_accessor :username, :email, :password, :password_confirmation

   validates :username,
               presence: true,
               uniqueness: true, 
               length: {maximum: 25}
   # validates :password,
   #             presence: true,
   #             length: { minimum: 6, message: 'must be at least 6 characters' }
   validates :email,
               presence: true,
               uniqueness: true
   validate :valid_email?

   # validates :invitation_id,
   #              presence: true

  def invitation_token
    invitation.token if invitation
  end
  
  def invitation_token=(token)
    self.invitation = Invitation.find_by_token(token)
  end

  private

  def valid_email?
    errors.add(:email, "This isn't a valid email.") unless email =~ /\A[\w+\-.]{3,}@[a-z\d\-.]{3,}\.[a-z]{2,}\z/i
  end

  def add_favorite(company)
    if self.favorites.where(company: company_id).empty?
      Favorite.create(user: self, company: company_id)
    end
  end
  
  def set_invitation_limit
    self.invitation_limit = 3
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  #before_action :set_company_and_discount

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @company = Company.new
    @discount = Discount.new
  end

  # GET /users/new
  def new
    # @user = User.new(:invitation_token => params[:invitation_token])
    # @user.email = @user.invitation.receipient_email if @user.invitation
    @user = User.new
    @company = Company.new
    @discount = Discount.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    create_helper
    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to companies_path, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    session.clear
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :username, :email, :password, :password_confirmation, :city, discounts_attributes: [
          :id, :discount_percent, :restrictions, company_attributes: [
            :id, :company_name, :store_pic, :logo
          ]
        ]
      )
    end

    def create_helper
      @user = User.new(user_params)
      @user.save
      @company = Company.find_or_create_by(company_name: params[:company][:company_name])

      # @company.update_attributes(params.require(:company).permit(:company_name, :store_pic, :logo))
      # @company.save 
    
      @discount = Discount.new(
        user_id: @user.id,
        company_id: @company.id,
        discount_percent: params[:discount][:discount_percent],
        restrictions: params[:restriction].join("\n"))
      @discount.save
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>City</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.city %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<!-- <h1>Discount Sharing</h1> -->



<div class="about-signup-container">
  <div id="about-budgie">
<!--     <div style="margin: 45px; color:white;">  -->
    <div id="about_signup_text"> 
      <h2 >Cheep is Cheap!</h2>
      <p>Budgie is a place where you can access a long list of employee discounts in your area.<br><br>All you've got to do in exchance, is share your employee discount with the community!</p>
      <button type="button" class="btn btn-custom btn-sm" id="signup-button">Sign Up Free!</button>
    </div> 
  </div>

  <div id="signup-form1">
<!--     <button id="about-button">About Us</button> -->
    <%= form_for(@user) do |user_form| %>
      <%= user_form.hidden_field :invitation_token %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
          <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= user_form.label :username %><br>
        <%= user_form.text_field :username %>
      </div>

      <div class="field">
        <%= user_form.label :email %><br>
        <%= user_form.text_field :email %>
      </div>

      <div class="field">
        <%= user_form.label :password %><br>
        <%= user_form.password_field :password %>
      </div>

      <div class="field">
        <%= user_form.label :password_confirmation %><br>
        <%= user_form.password_field :password_confirmation %>
      </div>
      </div>

      <div id="signup-form2">

      <div class="field">
        <%= user_form.label :city %><br>
        <%= user_form.text_field :city %>
      </div>
      
      <%= fields_for(@company) do |co| %>
        <div class="field">
          <%= co.label :company_name %><br>
          <%= co.text_field :company_name %>
        </div>
      <% end %>

      <%= fields_for(@discount) do |di| %>
        <div class="field">
          <%= di.label :discount_percent %><br>
          <%= di.text_field :discount_percent %>
        </div>

        <div class="input-field" id="restrictions">
          <%= di.label :restrictions %>
          <div class="restriction-wrapper">
            <div class="restriction-fields">
              <input type="text" name="restriction[]" value=""/>

              <a href="javascript:void(0);" class="add-restriction" title="Add Restriction">+</a>
            </div>
          </div>
        </div>
        

        
      <% end %>
      <div class="actions" style="margin-top: 10px;">
<!--         <button type="button" class="btn btn-custom btn-sm">Sumbit</button> -->
             <%= user_form.submit %>
      </div>
    <% end %>
  </div>
</div>


<div class="beta-mode-container">
  <div id="beta-mode-card">
<!--     <div style="margin: 15px; color:white;"> 
 -->     <div id="beta-text">
        <h2 id="beta-lock">Sign up for our beta version...</h2>
<!--       <img id="beta-lock" src="" alt=""> -->
      <h3>And start saving!</h3>
    </div>
  </div>

  <div id="beta-mode-form">
    <p>We are currently in beta mode. Please submit your email address, and we will notify you when we're ready to accept more users.</p> 

    <%= form_for Invitation.new do |f| %>
        <%= f.label :recipient_email, "Your Email:" %>
        <%= f.text_field :recipient_email %>
        <button type="button" class="btn btn-custom btn-sm">Submit</button></a>
<!--         <%= f.submit 'Submit' %> -->
    <% end %> 
  </div>
</div>

app/views/users/show.html.erb
<script>
$(document).ready(function() {
  $('.show-discount-form').click(function() {
    $('#discount-form').toggle();
    $('.show-discount-form').hide();
  });
})
</script>


<!--  -->
<!--  -->

<div class="container" >
<div class="row">
<% @user.discounts.each do |discount| %>
 
          <div class="col-md-4 col-sm-6" id="discount-<%=discount.id%>">
          
             <div class="card-container manual-flip">
                <div class="card">
                    <div class="front">
                        <div class="cover">
                            <%=image_tag("/rotating_card_thumb.png")%>
                        </div>
                        <div class="user">
                          <%=image_tag(("/rotating_card_profile.png"), class: "img-circle")%>
                        </div>
                        <div class="content">
                            <div class="main" id="discount-<%=discount.id%>">
                                <h3 class="name"><%= discount.company.company_name%></h3> 
                                
                                <h4 class="text-center"><%= discount.discount_percent %>% Discount</h4>
                             
                                <h4 class="text-center ct-heart">Restrictions: </h4>
                              <h6 class="text-center"><% discount.restrictions.split("\n").each do |restriction|%></h5> 
                                <h6 class="text-center"><li><%= restriction %></li></h5>
                                <h6 class="text-center"><% end %></h6>
                                <!-- end here -->
                              
                          
                            </div>
                           <div class="footer"> 
                          <button class="btn btn-danger btn-sm" href="#">
                          <%= link_to ' Delete ', [@user, discount], method: :delete, data: { confirm: 'Are you sure you would like to delete this discount?' }, class: "fa fa-trash-o fa-md"%>
                          </button>
                          <button class="btn btn-success btn-sm" onclick="rotateCard(this)"><i class="fa fa-mail-forward"></i> Update</button>
                          </div>
                          <!-- end here -->

                        </div>
                    </div> <!-- end front panel -->
                  
                    <div class="back">
                        <div class="header">
                        <div class="panel panel-default">
                         <div class="panel-heading clearfix">
   <button class="btn btn-danger btn-sm update-discount-button" data-id="<%= discount.id %>">Update</button>

                        </div> 
                        </div>
                        </div>
                        <div class="content">
                            <div class="main">

    <div class="panel panel-default user-discount-form">
   

    <%= form_for([@user, @discount], :html => {:id => 'discount-form'}) do |discount_form| %>

      <%= discount_form.hidden_field(:id) %>

      <%= fields_for(@company) do |co| %>
    <div class="modal-body">
    <form class="form-horizontal">
      
          <%= co.label :company_name %>
          <%= co.text_field :company_name %>
      
      <% end %>

      <div class="input-field">
        <%= discount_form.label :discount_percent %>
        <%= discount_form.text_field :discount_percent %>
      </div>

      <div class="input-field" id="restrictions">
        <%= discount_form.label :restrictions %>
        <div class="restriction-wrapper">
          <div class="restriction-fields">
            <input type="text" name="restriction[]" value=""/>

            <a href="javascript:void(0);" class="add-restriction" title="Add Restriction">+</a>
          </div>
        </div>
      </div>

      
      <div class="actions">
          <%= discount_form.submit "Save" %>
          
      </div>
      </form>
      </div>
    <% end %>
  
  </div>



                            
                            </div>
                        </div>
                        <div class="footer">
                            <button class="btn btn-simple" rel="tooltip" title="Flip Card" onclick="rotateCard(this)">
                                <i class="fa fa-reply"></i> Back
                            </button>
                        </div>
                    </div> <!-- end back panel -->
                </div> <!-- end card -->
            </div> 

            <!-- end card-container -->
            
        </div> <!-- end col sm 3 -->
<!--         <div class="col-sm-1"></div> -->


<!--  -->
<!--  -->


<!-- <div class="col-md-4 col-sm-6">
<div class="panel panel-default">
  <div class="panel-heading clearfix">
    <h3 class="panel-title pull-left">User Profile Update</h3>
    <!--   <a class="btn btn-default pull-right" href="#">
        <i class="fa fa-check"></i>
        Button
      </a> -->
<!--   </div>

  <div class="panel-body">
   <div class="modal-body">
    <form class="form-horizontal">

<div id="user-details-window">
  <div id="user-details">
    <p>
      <strong>Username:</strong>
      <%= @user.username %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Password:</strong>
      <%= @user.password %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @user.city %>
    </p>

   <!--  <button id="user-update-button">Update</button> -->
 <!--  </div>

  <div class="panel panel-default user-update-form">
    <%= render 'form' %>
  </div>
  </form>
  </div>

</div>





  </div>
  <div class="panel-footer">
   <button id="user-update-button">Update</button>
  </div>
</div>

</div> -->







<!--  -->
<!--  -->


<% end %>
</div>
</div>

<script type="text/javascript">
    $().ready(function(){
        $('[rel="tooltip"]').tooltip();
        
    });
    
    function rotateCard(btn){
        var $card = $(btn).closest('.card-container');
        console.log($card);
        if($card.hasClass('hover')){
            $card.removeClass('hover');
        } else {
            $card.addClass('hover');
        }
    }
</script>







<!-- <p id="notice"><%= notice %></p>

<div id="user-discounts"> -->

<!--   <% @user.discounts.each do |discount| %>

    <div class="user-discount-card" id="discount-<%=discount.id%>">
      <h3><%= discount.company.company_name %></h3>
      <h4><%= discount.discount_percent %>% discount</h4>
      <ul>
        <% discount.restrictions.split("\n").each do |restriction|%> 
            <li><%= restriction %></li>
          <% end %>
      </ul>
      <button class="update-discount-button" data-id="<%= discount.id %>">Update</button>
      <%= button_to 'Delete', [@user, discount], data: { confirm: 'Are you sure you would like to delete this discount?' },method: :delete %>
    </div>

  <% end %> -->

<!--   <div class="user-discount-card user-discount-form">
    <%= form_for([@user, @discount], :html => {:id => 'discount-form'}) do |discount_form| %>

      <%= discount_form.hidden_field(:id) %>

      <%= fields_for(@company) do |co| %>
        <div class="field">
          <%= co.label :company_name %>
          <%= co.text_field :company_name %>
        </div>
      <% end %>

      <div class="input-field">
        <%= discount_form.label :discount_percent %>
        <%= discount_form.text_field :discount_percent %>
      </div>

      <div class="input-field" id="restrictions">
        <%= discount_form.label :restrictions %>
        <div class="restriction-wrapper">
          <div class="restriction-fields">
            <input type="text" name="restriction[]" value=""/>

            <a href="javascript:void(0);" class="add-restriction" title="Add Restriction">+</a>
          </div>
        </div>
      </div>

      
      <div class="actions">
          <%= discount_form.submit "Save" %>
      </div>

    <% end %>
  
  </div>
</div> -->

<!-- <div id="user-details-window">
  <div id="user-details">
    <p>
      <strong>Username:</strong>
      <%= @user.username %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @user.email %>
    </p>

    <p>
      <strong>Password:</strong>
      <%= @user.password %>
    </p>

    <p>
      <strong>City:</strong>
      <%= @user.city %>
    </p>

    <button id="user-update-button">Update</button>
  </div>

  <div class="user-update-form">
    <%= render 'form' %>
  </div>
  

</div> -->